server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - RemoveResponseHeader=Server
      routes:
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin-service/**, /admin-service/health
          filters:
            - StripPrefix=0
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**, /auth-service/health
          filters:
            - StripPrefix=0
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart-service/**, /cart-service/health
          filters:
            - StripPrefix=0
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**, /order-service/health
          filters:
            - StripPrefix=0
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product-service/**, /product-service/health
          filters:
            - StripPrefix=0
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/search-service/**, /search-service/health
          filters:
            - StripPrefix=0
        - id: store-service
          uri: lb://store-service
          predicates:
            - Path=/store-service/**, /store-service/health
          filters:
            - StripPrefix=0
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**, /user-service/health
          filters:
            - StripPrefix=0
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
